package com.noto.app.ui.util

object Constants {
    const val Theme = "Theme"
    const val FolderId = "folder_id"
    const val FolderTitle = "folder_title"
    const val FilteredFolderIds = "filtered_folder_ids"
    const val SelectedFolderId = "selected_folder_id"
    const val NoteId = "note_id"
    const val Body = "body"
    const val IsDismissible = "is_dismissible"
    const val IsConfirmed = "on_confirm"
    const val VaultTimeout = "VaultTimeout"
    const val IsNoneEnabled = "is_none_enabled"
    const val IsPasscodeValid = "IsPasscodeValid"
    const val WidgetRadius = "WidgetRadius"
    const val NoteTitle = "NoteTitle"
    const val NoteBody = "NoteBody"
    const val ScrollPosition = "ScrollPosition"
    const val IsTitleVisible = "IsTitleVisible"
    const val IsBodyVisible = "IsBodyVisible"
    const val Title = "title"
    const val Model = "model"
    const val EmailType = "mailto:"
    const val DisableSelection = "DisableSelection"
    const val FilteringType = "FilteringType"
    const val SortingType = "SortingType"
    const val SortingOrder = "SortingOrder"
    const val GroupingType = "GroupingType"
    const val GroupingOrder = "GroupingOrder"
    const val QuickNoteFolderId = "quick_note_interface_id"
    const val MainInterfaceId = "main_interface_id"
    const val QuickNote = "quick_note"
    const val LogOut = "log_out"
    const val DeleteAccount = "delete_account"
    const val VerifyOtp = "verify_otp"
    const val IsMainFoldersEnabled = "is_main_folders_enabled"
    const val IsChildFoldersEnabled = "is_child_folders_enabled"
    const val AutoBackup = "AutoBackup"
    const val BackupPasscode = "BackupPasscode"
}